# Generated by Django 4.2.4 on 2024-01-01 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="law_for_platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "law_type_plat",
                    models.CharField(
                        max_length=50, verbose_name="Наименование закона движения"
                    ),
                ),
                (
                    "discription_law",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=500,
                        null=True,
                        verbose_name="Описание закона движения",
                    ),
                ),
                (
                    "discription_lawJSON",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Описание закона движения JSON",
                    ),
                ),
                ("dx", models.IntegerField(verbose_name="Движение по оси х")),
                ("dy", models.IntegerField(verbose_name="Движение по оси y")),
                ("dz", models.IntegerField(verbose_name="Движение по оси z")),
                ("phi", models.IntegerField(verbose_name="Угол поворота PHI")),
                ("theta", models.IntegerField(verbose_name="Угол поворота THETA")),
                ("psi", models.IntegerField(verbose_name="Угол поворота PSI")),
                (
                    "coordinates_t",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Сформированный закон движения",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="law_for_platform_wave_user_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закон движения для базового модуля",
                "verbose_name_plural": "Законы движения для базового модуля",
            },
        ),
        migrations.CreateModel(
            name="system_stewart_platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_system",
                    models.CharField(
                        max_length=50, verbose_name="Наименование системы"
                    ),
                ),
                (
                    "discription_system",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=500,
                        null=True,
                        verbose_name="Сформированный закон движения Системы",
                    ),
                ),
                (
                    "discription_systemJSON",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Сформированный закон движения Системы JSON",
                    ),
                ),
                (
                    "discription",
                    models.CharField(max_length=500, verbose_name="Описание системы"),
                ),
                (
                    "time_create",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_stewart_platform_user_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Система Stewart Platform",
                "verbose_name_plural": "Системы Stewart Platform",
            },
        ),
        migrations.CreateModel(
            name="stewart_platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_platform",
                    models.CharField(
                        max_length=50, verbose_name="Наименование базового модуля"
                    ),
                ),
                (
                    "discription_platform",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Сформированный закон движенияJSON",
                    ),
                ),
                (
                    "SERVO_HORN",
                    models.IntegerField(default=40, verbose_name="Длина кривошипа"),
                ),
                (
                    "SERVO_ROD",
                    models.IntegerField(default=200, verbose_name="Длина стержня"),
                ),
                (
                    "PLATFORM_RADIUS",
                    models.IntegerField(default=100, verbose_name="Радиус платформы"),
                ),
                (
                    "PLATFORM_DEFAULT_HEIGHT",
                    models.IntegerField(
                        default=195, verbose_name="Высота базового модуля"
                    ),
                ),
                (
                    "BASE_DEFAULT_HEIGHT",
                    models.IntegerField(default=0, verbose_name="Базовая высота"),
                ),
                (
                    "time_create",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stewart_platform_user_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "law_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="systemStewartPlatform.law_for_platform",
                        verbose_name="Закон движения платформы",
                    ),
                ),
                (
                    "system_stewart_platform",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="systemStewartPlatform.system_stewart_platform",
                        verbose_name="Система",
                    ),
                ),
            ],
            options={
                "verbose_name": "Базовый модуль",
                "verbose_name_plural": "Базовые модули",
            },
        ),
    ]
