# Generated by Django 4.2.4 on 2024-01-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemStewartPlatform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stewart_platform",
            name="discription_platformJSON",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Сформированный закон движенияJSON",
            ),
        ),
        migrations.AlterField(
            model_name="stewart_platform",
            name="discription_platform",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Сформированный закон движения",
            ),
        ),
    ]
